from django.urls import path

from apps.recording.views import (
    SessionRecordingListView,
    SessionRecordingStartView,
    SessionRecordingStopView,
)
from apps.streaming.views import (
    SessionStreamListView,
    SessionStreamStartView,
    SessionStreamStopView,
)
from apps.sources.views import (
    SceneSourceAttachView,
    SceneSourceDetachView,
    SceneSourceReorderView,
    SceneSourceVisibilityView,
    SessionRtmpSourceCreateView,
    SessionRtmpSourceDeleteView,
    SessionRtmpSourceListView,
    SessionSourceDetailView,
    SessionSourceListCreateView,
    SessionSourcePauseView,
    SessionSourcePlayView,
    SessionSourceSeekView,
    SessionSourceStopView,
)
from apps.scenes.views import (
    SessionSceneActivateView,
    SessionSceneDetailView,
    SessionSceneListCreateView,
)
from apps.sessions.views import (
    HealthView,
    MetricsView,
    SessionDetailView,
    SessionIngestView,
    SessionLayoutView,
    SessionListCreateView,
    ValidateInviteView,
)

urlpatterns = [
    path('health/', HealthView.as_view(), name='health'),
    path('metrics/', MetricsView.as_view(), name='metrics'),
    path('sessions/', SessionListCreateView.as_view(), name='session-list-create'),
    path('sessions/<uuid:session_id>/', SessionDetailView.as_view(), name='session-detail'),
    path(
        'sessions/<uuid:session_id>/layout/',
        SessionLayoutView.as_view(),
        name='session-layout',
    ),
    path(
        'sessions/<uuid:session_id>/validate-invite/',
        ValidateInviteView.as_view(),
        name='session-validate-invite',
    ),
    path(
        'sessions/<uuid:session_id>/ingest/',
        SessionIngestView.as_view(),
        name='session-ingest',
    ),
    path(
        'sessions/<uuid:session_id>/recordings/',
        SessionRecordingListView.as_view(),
        name='session-recording-list',
    ),
    path(
        'sessions/<uuid:session_id>/recordings/start/',
        SessionRecordingStartView.as_view(),
        name='session-recording-start',
    ),
    path(
        'sessions/<uuid:session_id>/recordings/stop/',
        SessionRecordingStopView.as_view(),
        name='session-recording-stop',
    ),
    path(
        'sessions/<uuid:session_id>/streams/',
        SessionStreamListView.as_view(),
        name='session-stream-list',
    ),
    path(
        'sessions/<uuid:session_id>/streams/start/',
        SessionStreamStartView.as_view(),
        name='session-stream-start',
    ),
    path(
        'sessions/<uuid:session_id>/streams/stop/',
        SessionStreamStopView.as_view(),
        name='session-stream-stop',
    ),
    path(
        'sessions/<uuid:session_id>/rtmp-sources/',
        SessionRtmpSourceListView.as_view(),
        name='session-rtmp-source-list',
    ),
    path(
        'sessions/<uuid:session_id>/rtmp-sources/add/',
        SessionRtmpSourceCreateView.as_view(),
        name='session-rtmp-source-add',
    ),
    path(
        'sessions/<uuid:session_id>/rtmp-sources/<str:source_id>/',
        SessionRtmpSourceDeleteView.as_view(),
        name='session-rtmp-source-delete',
    ),
    path(
        'sessions/<uuid:session_id>/sources/',
        SessionSourceListCreateView.as_view(),
        name='session-source-list-create',
    ),
    path(
        'sessions/<uuid:session_id>/sources/<str:source_id>/',
        SessionSourceDetailView.as_view(),
        name='session-source-detail',
    ),
    path(
        'sessions/<uuid:session_id>/sources/<str:source_id>/play/',
        SessionSourcePlayView.as_view(),
        name='session-source-play',
    ),
    path(
        'sessions/<uuid:session_id>/sources/<str:source_id>/pause/',
        SessionSourcePauseView.as_view(),
        name='session-source-pause',
    ),
    path(
        'sessions/<uuid:session_id>/sources/<str:source_id>/stop/',
        SessionSourceStopView.as_view(),
        name='session-source-stop',
    ),
    path(
        'sessions/<uuid:session_id>/sources/<str:source_id>/seek/',
        SessionSourceSeekView.as_view(),
        name='session-source-seek',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/sources/attach/',
        SceneSourceAttachView.as_view(),
        name='scene-source-attach',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/sources/<str:source_id>/',
        SceneSourceDetachView.as_view(),
        name='scene-source-detach',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/sources/<str:source_id>/visibility/',
        SceneSourceVisibilityView.as_view(),
        name='scene-source-visibility',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/sources/reorder/',
        SceneSourceReorderView.as_view(),
        name='scene-source-reorder',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/',
        SessionSceneListCreateView.as_view(),
        name='session-scene-list-create',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/',
        SessionSceneDetailView.as_view(),
        name='session-scene-detail',
    ),
    path(
        'sessions/<uuid:session_id>/scenes/<uuid:scene_id>/activate/',
        SessionSceneActivateView.as_view(),
        name='session-scene-activate',
    ),
]
