# Generated by Django 5.0.1 on 2026-07-11 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECORDING', 'Recording'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='RECORDING', max_length=16)),
                ('file_path', models.CharField(max_length=512)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='studio_sessions.studiosession')),
            ],
            options={
                'db_table': 'session_recordings',
                'ordering': ['-started_at'],
            },
        ),
    ]
