# Generated by Django 5.0.1 on 2026-07-31 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio_sessions', '0003_studiosession_graphics_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('scene_type', models.CharField(choices=[('CAMERA', 'Camera'), ('COUNTDOWN', 'Countdown')], max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('layout', models.CharField(blank=True, choices=[('CONTAIN', 'Contain'), ('COVER', 'Cover'), ('THUMBNAIL', 'Thumbnail'), ('GRID', 'Grid'), ('SIDE_BY_SIDE', 'Side by side'), ('HALFSCREEN', 'Half screen'), ('SPOTLIGHT', 'Spotlight'), ('CINEMA', 'Cinema'), ('PICTURE_IN_PICTURE', 'Picture in picture'), ('OVERLAY', 'Overlay'), ('FULLSCREEN', 'Fullscreen')], default='', max_length=32)),
                ('graphics_config', models.JSONField(blank=True, default=dict)),
                ('devices_config', models.JSONField(blank=True, default=dict)),
                ('sources_config', models.JSONField(blank=True, default=dict)),
                ('background_music_config', models.JSONField(blank=True, default=dict)),
                ('countdown_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countdown_target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countdown_references', to='scenes.studioscene')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='studio_sessions.studiosession')),
            ],
            options={
                'db_table': 'studio_scenes',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
