# Generated by Django 5.0.1 on 2026-07-11 07:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_type', models.CharField(choices=[('RTMP', 'RTMP'), ('HLS', 'HLS')], max_length=8)),
                ('destination_url', models.CharField(blank=True, max_length=512)),
                ('output_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='LIVE', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='studio_sessions.studiosession')),
            ],
            options={
                'db_table': 'session_streams',
                'ordering': ['-started_at'],
            },
        ),
    ]
