# Generated by Django 5.0.1 on 2026-07-11 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host_display_name', models.CharField(max_length=120)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('layout', models.CharField(choices=[('CONTAIN', 'Contain'), ('THUMBNAIL', 'Thumbnail')], default='CONTAIN', max_length=16)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='CREATED', max_length=16)),
                ('mediasoup_compositor_peer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studio_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
