# Generated by Django 5.0.1 on 2026-07-31 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
        ('studio_sessions', '0003_studiosession_graphics_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosession',
            name='active_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scenes.studioscene'),
        ),
    ]
